### ISSUE TITLE
unstable behaviour on embedded client

### ISSUE THREAD

**Issue by pressla** [SocketCluster/socketcluster-client#4]
I am using the socketcluster client on openwrt routers and they are logging quite a lot by the socketcluster. I am running nodejs 0.10.28 on them (mips architecture). It is 100% out traffic, so no subscriptions are there currently. but with frequencies at 200ms I get consistently an exception.

has anyone an idea?

thanks

/node_modules/socketcluster-client/lib/scsocket.js:311
      throw err;
            ^
Error: xhr poll error
    at XHR.Transport.onError (/node_modules/socketcluster-client/node_modules/engine.io-client/lib/transport.js:57:13)
    at Request.<anonymous> (/node_modules/socketcluster-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:112:10)
    at Request.Emitter.emit (/node_modules/socketcluster-client/node_modules/engine.io-client/node_modules/component-emitter/index.js:134:20)
    at Request.onError (/node_modules/socketcluster-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:247:8)
    at null._onTimeout (/node_modules/socketcluster-client/node_modules/engine.io-client/lib/transports/polling-xhr.js:194:18)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

**Comment by jondubois** [comment]
No idea, I couldn't reproduce this.

All I can say is that the most common 'xhr poll error' happens when you try to use the SC v1 client with the SC v2 server (the two have a incompatible protocol).

**Comment by jondubois** [comment]
@pressla Did you manage to figure out this issue?
